# Generated by Django 4.1.7 on 2023-05-23 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stooore', '0004_product_availability'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'ordering': ['brand_name']},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_name']},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['product_name']},
        ),
    ]
