# Generated by Django 4.1.7 on 2023-05-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stooore', '0010_order_quantity_alter_brand_brand_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(),
        ),
    ]
